/* ============================================
   Reborn Infinity - js/skills/combatSkills.js
   戦闘系スキルデータ
   ============================================ */

const COMBAT_SKILLS = [
  {
    id: 'strength',
    name: '体力',
    category: 'combat',
    icon: '💪',
    desc: '肉体的な強さを鍛える。最大HPが上がる。',
    xpBase: 50,
    effect: { stat: 'hp', perLevel: 15 },
    reqFame: 0,
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'sword_mastery',
    name: '剣術',
    category: 'combat',
    icon: '⚔️',
    desc: '剣の扱いを磨く。ATKが上がる。',
    xpBase: 80,
    effect: { stat: 'atk', perLevel: 3 },
    reqFame: 10,
    unlockDesc: '名声10が必要',
  },
  {
    id: 'shield_mastery',
    name: '盾術',
    category: 'combat',
    icon: '🛡️',
    desc: '盾の使い方を磨く。DEFが上がる。',
    xpBase: 80,
    effect: { stat: 'def', perLevel: 2 },
    reqFame: 10,
    unlockDesc: '名声10が必要',
  },
  {
    id: 'critical_strike',
    name: '会心一撃',
    category: 'combat',
    icon: '⚡',
    desc: 'クリティカル率が上がる。',
    xpBase: 150,
    effect: { stat: 'critRate', perLevel: 0.005 },
    reqFame: 20,
    unlockDesc: '名声20が必要',
  },
  {
    id: 'critical_power',
    name: '会心強化',
    category: 'combat',
    icon: '💥',
    desc: 'クリティカルダメージ倍率が上がる。',
    xpBase: 200,
    effect: { stat: 'critMult', perLevel: 0.05 },
    reqFame: 30,
    reqSkill: { critical_strike: 10 },
    unlockDesc: '名声30・会心一撃Lv10',
  },
  {
    id: 'endurance',
    name: '忍耐力',
    category: 'combat',
    icon: '🔰',
    desc: '苦しい状況でも戦い続ける精神力。寿命が上がる。',
    xpBase: 200,
    effect: { stat: 'lifespan', perLevel: 5 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'berserker_rage',
    name: '戦闘狂',
    category: 'combat',
    icon: '🔥',
    desc: 'HP低下時にATKが上昇する。',
    xpBase: 300,
    effect: { stat: 'rageAtk', perLevel: 2 },
    reqFame: 40,
    reqSkill: { sword_mastery: 20 },
    unlockDesc: '名声40・剣術Lv20',
  },
  {
    id: 'counter_attack',
    name: '反撃',
    category: 'combat',
    icon: '↩️',
    desc: '被ダメージ時に反撃できる確率が上がる。',
    xpBase: 350,
    effect: { stat: 'counterRate', perLevel: 0.01 },
    reqFame: 45,
    reqSkill: { shield_mastery: 20 },
    unlockDesc: '名声45・盾術Lv20',
  },
  {
    id: 'iron_body',
    name: '鉄の肉体',
    category: 'combat',
    icon: '🦾',
    desc: '鋼のような肉体を鍛える。HPとDEFが上がる。',
    xpBase: 250,
    effect: { stat: 'hp', perLevel: 20, stat2: 'def', perLevel2: 1 },
    reqFame: 35,
    reqSkill: { strength: 15 },
    unlockDesc: '名声35・体力Lv15',
  },
  {
    id: 'weapon_mastery',
    name: '武器熟練',
    category: 'combat',
    icon: '🗡️',
    desc: 'あらゆる武器を使いこなす。ATKが大きく上がる。',
    xpBase: 400,
    effect: { stat: 'atk', perLevel: 5 },
    reqFame: 50,
    reqSkill: { sword_mastery: 20 },
    unlockDesc: '名声50・剣術Lv20',
  },
];

Object.freeze(COMBAT_SKILLS);
