/* ============================================
   Reborn Infinity - js/skills/craftSkills.js
   クラフト系スキルデータ
   ============================================ */

const CRAFT_SKILLS = [
  {
    id: 'crafting',
    name: 'クラフト',
    category: 'craft',
    icon: '🔨',
    desc: '物を作る基礎技術。クラフト成功率が上がる。',
    xpBase: 70,
    effect: { stat: 'craft', perLevel: 0.05 },
    reqFame: 0,
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'smithing',
    name: '鍛冶',
    category: 'craft',
    icon: '⚒️',
    desc: '金属加工の技術。武器・防具のクラフト品質が上がる。',
    xpBase: 120,
    effect: { stat: 'craft', perLevel: 0.08 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'alchemy',
    name: '錬金術',
    category: 'craft',
    icon: '⚗️',
    desc: '素材を変換・合成する技術。素材効率が上がる。',
    xpBase: 150,
    effect: { stat: 'matConvert', perLevel: 0.05 },
    reqFame: 20,
    unlockDesc: '名声20が必要',
  },
  {
    id: 'enchanting',
    name: '付与魔法',
    category: 'craft',
    icon: '✨',
    desc: '装備に魔法の力を付与する。装備効果が上がる。',
    xpBase: 250,
    effect: { stat: 'equipEffect', perLevel: 0.05 },
    reqFame: 35,
    reqSkill: { alchemy: 10 },
    unlockDesc: '名声35・錬金術Lv10',
  },
  {
    id: 'mass_production',
    name: '量産化',
    category: 'craft',
    icon: '🏭',
    desc: 'クラフト速度が上がる。一度に多く作れる。',
    xpBase: 300,
    effect: { stat: 'craftSpeed', perLevel: 0.08 },
    reqFame: 40,
    reqSkill: { crafting: 20, smithing: 10 },
    unlockDesc: '名声40・クラフトLv20・鍛冶Lv10',
  },
  {
    id: 'material_efficiency',
    name: '素材節約',
    category: 'craft',
    icon: '♻️',
    desc: 'クラフト時の素材消費量が減る。',
    xpBase: 350,
    effect: { stat: 'matSave', perLevel: 0.03 },
    reqFame: 45,
    reqSkill: { alchemy: 20 },
    unlockDesc: '名声45・錬金術Lv20',
  },
  {
    id: 'master_craft',
    name: '匠の技',
    category: 'craft',
    icon: '🏆',
    desc: 'クラフト品の品質が上がり、より強い効果を持つ。',
    xpBase: 500,
    effect: { stat: 'craft', perLevel: 0.15 },
    reqFame: 70,
    reqSkill: { smithing: 30, enchanting: 20 },
    unlockDesc: '名声70・鍛冶Lv30・付与魔法Lv20',
  },
];

Object.freeze(CRAFT_SKILLS);
