/* ============================================
   Reborn Infinity - js/skills/magicSkills.js
   魔法系スキルデータ
   ============================================ */

const MAGIC_SKILLS = [
  {
    id: 'mana_pool',
    name: 'マナプール',
    category: 'magic',
    icon: '💧',
    desc: '最大MPが上がる。',
    xpBase: 100,
    effect: { stat: 'mp', perLevel: 8 },
    reqFame: 12,
    unlockDesc: '名声12が必要',
  },
  {
    id: 'fire_magic',
    name: '火魔法',
    category: 'magic',
    icon: '🔥',
    desc: '火属性の魔法攻撃力が上がる。',
    xpBase: 120,
    effect: { stat: 'fireDmg', perLevel: 5 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'ice_magic',
    name: '氷魔法',
    category: 'magic',
    icon: '❄️',
    desc: '氷属性の魔法攻撃力が上がる。',
    xpBase: 120,
    effect: { stat: 'iceDmg', perLevel: 5 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'lightning_magic',
    name: '雷魔法',
    category: 'magic',
    icon: '⚡',
    desc: '雷属性の魔法攻撃力が上がる。',
    xpBase: 120,
    effect: { stat: 'lightDmg', perLevel: 5 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'mana_regen',
    name: 'マナ回復',
    category: 'magic',
    icon: '🌊',
    desc: 'MP自動回復速度が上がる。',
    xpBase: 180,
    effect: { stat: 'mpRegen', perLevel: 0.01 },
    reqFame: 25,
    reqSkill: { mana_pool: 10 },
    unlockDesc: '名声25・マナプールLv10',
  },
  {
    id: 'spell_mastery',
    name: '魔法熟練',
    category: 'magic',
    icon: '📖',
    desc: 'すべての魔法の威力が上がる。',
    xpBase: 300,
    effect: { stat: 'magicDmg', perLevel: 0.05 },
    reqFame: 40,
    reqSkill: { fire_magic: 15, ice_magic: 15 },
    unlockDesc: '名声40・火/氷魔法Lv15',
  },
  {
    id: 'arcane_power',
    name: '秘術の力',
    category: 'magic',
    icon: '🌟',
    desc: 'XP獲得量と魔法攻撃力が上がる。',
    xpBase: 400,
    effect: { stat: 'xp', perLevel: 0.05, stat2: 'magicDmg', perLevel2: 0.03 },
    reqFame: 55,
    reqSkill: { spell_mastery: 20 },
    unlockDesc: '名声55・魔法熟練Lv20',
  },
  {
    id: 'void_magic',
    name: '虚無魔法',
    category: 'magic',
    icon: '🕳️',
    desc: '虚無の力を操る。全ての魔法能力が飛躍的に上昇。',
    xpBase: 800,
    effect: { stat: 'magicDmg', perLevel: 0.10, stat2: 'mp', perLevel2: 20 },
    reqFame: 200,
    reqSkill: { arcane_power: 30 },
    reqRebirth: 1,
    unlockDesc: '転生1回・名声200・秘術の力Lv30',
  },
];

Object.freeze(MAGIC_SKILLS);
