/* ============================================
   Reborn Infinity - js/skills/lifeSkills.js
   生活系スキルデータ
   ============================================ */

const LIFE_SKILLS = [
  {
    id: 'agility',
    name: '敏捷性',
    category: 'life',
    icon: '💨',
    desc: '素早さを鍛える。XP獲得量が上がる。',
    xpBase: 80,
    effect: { stat: 'xp', perLevel: 0.05 },
    reqFame: 0,
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'wisdom',
    name: '知恵',
    category: 'life',
    icon: '🧠',
    desc: '知識と判断力を磨く。コイン獲得量が上がる。',
    xpBase: 120,
    effect: { stat: 'coin', perLevel: 0.10 },
    reqFame: 0,
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'charisma',
    name: 'カリスマ',
    category: 'life',
    icon: '✨',
    desc: '人を惹きつける魅力。名声獲得量が上がる。',
    xpBase: 150,
    effect: { stat: 'fame', perLevel: 0.10 },
    reqFame: 5,
    unlockDesc: '名声5が必要',
  },
  {
    id: 'luck',
    name: '幸運',
    category: 'life',
    icon: '🍀',
    desc: '幸運を引き寄せる力。素材ドロップ率が上がる。',
    xpBase: 200,
    effect: { stat: 'luck', perLevel: 0.05 },
    reqFame: 10,
    unlockDesc: '名声10が必要',
  },
  {
    id: 'meditation',
    name: '瞑想',
    category: 'life',
    icon: '🧘',
    desc: '心を落ち着かせる修行。MPとHP回復が上がる。',
    xpBase: 180,
    effect: { stat: 'mpRegen', perLevel: 0.01, stat2: 'hpRegen', perLevel2: 0.01 },
    reqFame: 15,
    unlockDesc: '名声15が必要',
  },
  {
    id: 'longevity',
    name: '長寿の秘訣',
    category: 'life',
    icon: '🌿',
    desc: '健康的な生活習慣で寿命を延ばす。',
    xpBase: 300,
    effect: { stat: 'lifespan', perLevel: 3 },
    reqFame: 30,
    reqSkill: { meditation: 15 },
    unlockDesc: '名声30・瞑想Lv15',
  },
  {
    id: 'negotiation',
    name: '交渉術',
    category: 'life',
    icon: '🤝',
    desc: '商談や交渉を有利に進める。コインと名声が上がる。',
    xpBase: 250,
    effect: { stat: 'coin', perLevel: 0.08, stat2: 'fame', perLevel2: 0.05 },
    reqFame: 25,
    reqSkill: { charisma: 10 },
    unlockDesc: '名声25・カリスマLv10',
  },
  {
    id: 'leadership',
    name: 'リーダーシップ',
    category: 'life',
    icon: '👑',
    desc: '人を束ねる力。名声とコインが大幅増加。',
    xpBase: 400,
    effect: { stat: 'fame', perLevel: 0.15, stat2: 'coin', perLevel2: 0.10 },
    reqFame: 60,
    reqSkill: { charisma: 20, negotiation: 15 },
    unlockDesc: '名声60・カリスマLv20・交渉術Lv15',
  },
];

Object.freeze(LIFE_SKILLS);
