/* ============================================
   Reborn Infinity - js/jobs/advancedJobs.js
   上級職業データ（Rank2）
   ============================================ */

const ADVANCED_JOBS = [
  {
    id: 'knight',
    name: '騎士',
    rank: 2,
    category: 'combat',
    icon: '🛡️',
    desc: '名誉ある戦士。ATKとDEFが大きく上がる。',
    income: 20,
    xpBase: 600,
    reqFame: 30,
    reqLevel: { soldier: 10 },
    bonuses: { atk: 8, def: 5, fame: 0.10 },
    unlockDesc: '名声30・兵士Lv10',
  },
  {
    id: 'mage',
    name: '魔法使い',
    rank: 2,
    category: 'magic',
    icon: '✨',
    desc: '本格的な魔法を扱う。MPとXPが大きく上がる。',
    income: 22,
    xpBase: 650,
    reqFame: 35,
    reqLevel: { apprentice_mage: 10 },
    bonuses: { mp: 25, xp: 0.15 },
    unlockDesc: '名声35・魔法使い見習いLv10',
  },
  {
    id: 'assassin',
    name: '暗殺者',
    rank: 2,
    category: 'combat',
    icon: '🌑',
    desc: '影に潜み一撃必殺を狙う。クリティカルに特化。',
    income: 25,
    xpBase: 580,
    reqFame: 30,
    reqLevel: { thief: 10 },
    bonuses: { critRate: 0.08, critMult: 0.3, atk: 5 },
    unlockDesc: '名声30・盗賊Lv10',
  },
  {
    id: 'ranger',
    name: 'レンジャー',
    rank: 2,
    category: 'explore',
    icon: '🌲',
    desc: '野を駆ける探索者。探索・発見に特化。',
    income: 18,
    xpBase: 560,
    reqFame: 25,
    reqLevel: { archer: 10, scout: 5 },
    bonuses: { explore: 0.20, mat: 0.10, luck: 0.05 },
    unlockDesc: '名声25・弓使いLv10・斥候Lv5',
  },
  {
    id: 'blacksmith',
    name: '鍛冶師',
    rank: 2,
    category: 'craft',
    icon: '⚒️',
    desc: '優れた武器・防具を鍛える職人。',
    income: 20,
    xpBase: 620,
    reqFame: 25,
    reqLevel: { blacksmith_apprentice: 10 },
    bonuses: { craft: 0.20, mat: 0.08, atk: 3 },
    unlockDesc: '名声25・鍛冶師見習いLv10',
  },
  {
    id: 'priest',
    name: '神官',
    rank: 2,
    category: 'divine',
    icon: '⛪',
    desc: '神に仕える聖職者。HPと名声獲得が上がる。',
    income: 18,
    xpBase: 640,
    reqFame: 35,
    reqLevel: { healer: 10, monk: 5 },
    bonuses: { hp: 30, hpRegen: 0.15, fame: 0.12 },
    unlockDesc: '名声35・治癒師Lv10・修行僧Lv5',
  },
  {
    id: 'merchant',
    name: '商人',
    rank: 2,
    category: 'commerce',
    icon: '💰',
    desc: '大規模な商売を展開する。コイン獲得が大幅増加。',
    income: 30,
    xpBase: 700,
    reqFame: 40,
    reqLevel: { merchant_apprentice: 10 },
    bonuses: { coin: 0.25 },
    unlockDesc: '名声40・商人見習いLv10',
  },
  {
    id: 'alchemist',
    name: '錬金術師',
    rank: 2,
    category: 'craft',
    icon: '🧪',
    desc: '素材を自在に変換・強化する。',
    income: 22,
    xpBase: 660,
    reqFame: 35,
    reqLevel: { alchemist_apprentice: 10 },
    bonuses: { craft: 0.18, mat: 0.12, xp: 0.08 },
    unlockDesc: '名声35・錬金術師見習いLv10',
  },
  {
    id: 'berserker',
    name: 'バーサーカー',
    rank: 2,
    category: 'combat',
    icon: '🔥',
    desc: '怒りの力で戦う狂戦士。ATKが突出して高い。',
    income: 24,
    xpBase: 590,
    reqFame: 30,
    reqLevel: { soldier: 10 },
    bonuses: { atk: 15, hp: -10, critRate: 0.05 },
    unlockDesc: '名声30・兵士Lv10',
  },
  {
    id: 'scholar',
    name: '学者',
    rank: 2,
    category: 'life',
    icon: '📚',
    desc: '知識を極める学者。全XP獲得量が大幅増加。',
    income: 15,
    xpBase: 680,
    reqFame: 35,
    reqLevel: { monk: 10 },
    bonuses: { xp: 0.20, skillXp: 0.15 },
    unlockDesc: '名声35・修行僧Lv10',
  },
];

Object.freeze(ADVANCED_JOBS);
