/* ============================================
   Reborn Infinity - js/jobs/apprenticeJobs.js
   見習い級職業データ（Rank1）
   ============================================ */

const APPRENTICE_JOBS = [
  {
    id: 'soldier',
    name: '兵士',
    rank: 1,
    category: 'combat',
    icon: '⚔️',
    desc: '戦場に立つ基本の戦士。ATKが上がる。',
    income: 8,
    xpBase: 300,
    reqFame: 10,
    reqLevel: { villager: 5 },
    bonuses: { atk: 3, fame: 0.05 },
    unlockDesc: '名声10・村人Lv5',
  },
  {
    id: 'apprentice_mage',
    name: '魔法使い見習い',
    rank: 1,
    category: 'magic',
    icon: '🔮',
    desc: '魔法の基礎を学ぶ。MPが増える。',
    income: 7,
    xpBase: 320,
    reqFame: 12,
    reqLevel: { villager: 5 },
    bonuses: { mp: 10, xp: 0.05 },
    unlockDesc: '名声12・村人Lv5',
  },
  {
    id: 'thief',
    name: '盗賊',
    rank: 1,
    category: 'combat',
    icon: '🗡️',
    desc: '素早い動きで敵の隙を突く。クリティカル率が上がる。',
    income: 9,
    xpBase: 280,
    reqFame: 10,
    reqLevel: { villager: 5 },
    bonuses: { critRate: 0.03, atk: 2 },
    unlockDesc: '名声10・村人Lv5',
  },
  {
    id: 'archer',
    name: '弓使い',
    rank: 1,
    category: 'combat',
    icon: '🏹',
    desc: '遠距離から矢を放つ。探索速度が上がる。',
    income: 8,
    xpBase: 290,
    reqFame: 10,
    reqLevel: { woodcutter: 3 },
    bonuses: { atk: 2, explore: 0.05 },
    unlockDesc: '名声10・木こりLv3',
  },
  {
    id: 'blacksmith_apprentice',
    name: '鍛冶師見習い',
    rank: 1,
    category: 'craft',
    icon: '🔨',
    desc: '金属を加工して武器や道具を作る。クラフト効率が上がる。',
    income: 8,
    xpBase: 310,
    reqFame: 8,
    reqLevel: { miner: 3 },
    bonuses: { craft: 0.10, mat: 0.05 },
    unlockDesc: '名声8・鉱夫Lv3',
  },
  {
    id: 'healer',
    name: '治癒師見習い',
    rank: 1,
    category: 'magic',
    icon: '💊',
    desc: '傷ついた人を癒す。HP回復量が上がる。',
    income: 7,
    xpBase: 330,
    reqFame: 12,
    reqLevel: { gatherer: 3 },
    bonuses: { hpRegen: 0.10, mp: 5 },
    unlockDesc: '名声12・採集者Lv3',
  },
  {
    id: 'scout',
    name: '斥候',
    rank: 1,
    category: 'explore',
    icon: '🔭',
    desc: '先行偵察を行う。探索速度と発見率が上がる。',
    income: 7,
    xpBase: 270,
    reqFame: 8,
    reqLevel: { gatherer: 3 },
    bonuses: { explore: 0.10, luck: 0.03 },
    unlockDesc: '名声8・採集者Lv3',
  },
  {
    id: 'merchant_apprentice',
    name: '商人見習い',
    rank: 1,
    category: 'commerce',
    icon: '💼',
    desc: '商売の基礎を学ぶ。コイン獲得量が上がる。',
    income: 10,
    xpBase: 350,
    reqFame: 15,
    reqLevel: { trader: 5 },
    bonuses: { coin: 0.12 },
    unlockDesc: '名声15・行商人Lv5',
  },
  {
    id: 'alchemist_apprentice',
    name: '錬金術師見習い',
    rank: 1,
    category: 'craft',
    icon: '⚗️',
    desc: '素材を変換する錬金術を学ぶ。',
    income: 8,
    xpBase: 340,
    reqFame: 15,
    reqLevel: { cook: 3, gatherer: 3 },
    bonuses: { craft: 0.08, matConvert: 0.05 },
    unlockDesc: '名声15・料理人/採集者Lv3',
  },
  {
    id: 'monk',
    name: '修行僧',
    rank: 1,
    category: 'divine',
    icon: '🙏',
    desc: '心身を鍛え精神力を高める。XP獲得量が上がる。',
    income: 6,
    xpBase: 360,
    reqFame: 15,
    reqLevel: { villager: 10 },
    bonuses: { xp: 0.10, lifespan: 2 },
    unlockDesc: '名声15・村人Lv10',
  },
];

Object.freeze(APPRENTICE_JOBS);
