/* ============================================
   Reborn Infinity - js/jobs/divineJobs.js
   神格級職業データ（Rank5）転生後解放
   ============================================ */

const DIVINE_JOBS = [
  {
    id: 'god_warrior',
    name: '神戦士',
    rank: 5,
    category: 'combat',
    icon: '⚡',
    desc: '神の力を宿した究極の戦士。全戦闘能力が神域に達する。',
    income: 500,
    xpBase: 8000,
    reqFame: 300,
    reqRebirth: 1,
    reqLevel: { hero: 30 },
    bonuses: { atk: 80, def: 60, hp: 300, critRate: 0.20 },
    unlockDesc: '転生1回・名声300・英雄Lv30',
  },
  {
    id: 'god_mage',
    name: '神魔導士',
    rank: 5,
    category: 'magic',
    icon: '🌌',
    desc: '魔法の神。全魔法能力が人知を超える。',
    income: 520,
    xpBase: 8500,
    reqFame: 320,
    reqRebirth: 1,
    reqLevel: { grand_wizard: 30 },
    bonuses: { mp: 250, xp: 0.60, atk: 50, skillXp: 0.40 },
    unlockDesc: '転生1回・名声320・大魔法使いLv30',
  },
  {
    id: 'deity',
    name: '神格者',
    rank: 5,
    category: 'divine',
    icon: '✨',
    desc: '神そのものに近づいた存在。あらゆる能力が飛躍的に向上。',
    income: 600,
    xpBase: 10000,
    reqFame: 400,
    reqRebirth: 2,
    reqLevel: { saint: 30 },
    bonuses: { hp: 500, lifespan: 30, fame: 0.50, xp: 0.40, coin: 0.30 },
    unlockDesc: '転生2回・名声400・聖人Lv30',
  },
  {
    id: 'world_creator',
    name: '世界の創造者',
    rank: 5,
    category: 'special',
    icon: '🌍',
    desc: '世界を創造する力を持つ存在。全リソース獲得が最高峰。',
    income: 800,
    xpBase: 12000,
    reqFame: 500,
    reqRebirth: 3,
    reqLevel: { deity: 20 },
    bonuses: { coin: 0.80, xp: 0.70, mat: 0.60, fame: 0.60 },
    unlockDesc: '転生3回・名声500・神格者Lv20',
  },
  {
    id: 'cosmic_sage',
    name: '宇宙の賢者',
    rank: 5,
    category: 'life',
    icon: '🌠',
    desc: '宇宙の理を知る超越的な賢者。XPとスキルXPが極限まで上昇。',
    income: 550,
    xpBase: 9000,
    reqFame: 350,
    reqRebirth: 1,
    reqLevel: { grand_wizard: 20, saint: 20 },
    bonuses: { xp: 0.80, skillXp: 0.70, mp: 200, lifespan: 20 },
    unlockDesc: '転生1回・名声350・大魔法使い/聖人Lv20',
  },
];

Object.freeze(DIVINE_JOBS);
