/* ============================================
   Reborn Infinity - js/jobs/eliteJobs.js
   精鋭級職業データ（Rank3）
   ============================================ */

const ELITE_JOBS = [
  {
    id: 'paladin',
    name: '聖騎士',
    rank: 3,
    category: 'combat',
    icon: '⚜️',
    desc: '神の加護を受けた最強の騎士。ATK・DEF・HP全て高い。',
    income: 50,
    xpBase: 1200,
    reqFame: 60,
    reqLevel: { knight: 20, priest: 10 },
    bonuses: { atk: 15, def: 12, hp: 50, fame: 0.15 },
    unlockDesc: '名声60・騎士Lv20・神官Lv10',
  },
  {
    id: 'archmage',
    name: '大魔導士',
    rank: 3,
    category: 'magic',
    icon: '🌟',
    desc: '伝説の魔法使い。MP・XP・魔法攻撃力が飛躍的に上昇。',
    income: 55,
    xpBase: 1300,
    reqFame: 70,
    reqLevel: { mage: 20 },
    bonuses: { mp: 60, xp: 0.25, atk: 10 },
    unlockDesc: '名声70・魔法使いLv20',
  },
  {
    id: 'shadow_master',
    name: '影の主',
    rank: 3,
    category: 'combat',
    icon: '🌑',
    desc: '暗殺の頂点に立つ者。クリティカルで大ダメージ。',
    income: 52,
    xpBase: 1150,
    reqFame: 60,
    reqLevel: { assassin: 20 },
    bonuses: { critRate: 0.15, critMult: 0.8, atk: 12 },
    unlockDesc: '名声60・暗殺者Lv20',
  },
  {
    id: 'warlord',
    name: '武将',
    rank: 3,
    category: 'combat',
    icon: '🏯',
    desc: '軍を率いる指揮官。戦闘・名声・コイン全てに強い。',
    income: 60,
    xpBase: 1250,
    reqFame: 65,
    reqLevel: { knight: 15, berserker: 10 },
    bonuses: { atk: 12, def: 8, fame: 0.20, coin: 0.10 },
    unlockDesc: '名声65・騎士Lv15・バーサーカーLv10',
  },
  {
    id: 'grand_merchant',
    name: '大商人',
    rank: 3,
    category: 'commerce',
    icon: '👑',
    desc: '国を動かすほどの巨大商会を持つ。コイン収入が圧倒的。',
    income: 80,
    xpBase: 1400,
    reqFame: 75,
    reqLevel: { merchant: 20 },
    bonuses: { coin: 0.40, fame: 0.15 },
    unlockDesc: '名声75・商人Lv20',
  },
  {
    id: 'master_alchemist',
    name: '錬金術の達人',
    rank: 3,
    category: 'craft',
    icon: '🔬',
    desc: '素材を自在に操る錬金術の極み。',
    income: 48,
    xpBase: 1200,
    reqFame: 60,
    reqLevel: { alchemist: 20, blacksmith: 10 },
    bonuses: { craft: 0.35, mat: 0.20, xp: 0.10 },
    unlockDesc: '名声60・錬金術師Lv20・鍛冶師Lv10',
  },
  {
    id: 'sage',
    name: '賢者',
    rank: 3,
    category: 'life',
    icon: '📖',
    desc: '全ての知識を持つ賢者。XP・スキルXP・MP全てに優れる。',
    income: 45,
    xpBase: 1350,
    reqFame: 70,
    reqLevel: { scholar: 20, archmage: 5 },
    bonuses: { xp: 0.30, skillXp: 0.25, mp: 30 },
    unlockDesc: '名声70・学者Lv20・大魔導士Lv5',
  },
  {
    id: 'high_priest',
    name: '大神官',
    rank: 3,
    category: 'divine',
    icon: '✝️',
    desc: '神殿を統括する最高位の神官。寿命と名声が大幅増加。',
    income: 50,
    xpBase: 1280,
    reqFame: 70,
    reqLevel: { priest: 20 },
    bonuses: { hp: 60, lifespan: 8, fame: 0.25 },
    unlockDesc: '名声70・神官Lv20',
  },
  {
    id: 'beastmaster',
    name: '獣使い',
    rank: 3,
    category: 'explore',
    icon: '🐉',
    desc: '魔物を従える者。ペット能力と探索力が飛躍的に上がる。',
    income: 48,
    xpBase: 1180,
    reqFame: 60,
    reqLevel: { ranger: 20 },
    bonuses: { petXp: 0.25, explore: 0.30, mat: 0.15 },
    unlockDesc: '名声60・レンジャーLv20',
  },
  {
    id: 'runeblade',
    name: 'ルーンブレード',
    rank: 3,
    category: 'combat',
    icon: '🗡️',
    desc: 'ルーン文字を刻んだ剣を操る戦士。ATKとMPを兼ね備える。',
    income: 55,
    xpBase: 1220,
    reqFame: 65,
    reqLevel: { knight: 10, mage: 10 },
    bonuses: { atk: 18, mp: 20, xp: 0.10 },
    unlockDesc: '名声65・騎士Lv10・魔法使いLv10',
  },
];

Object.freeze(ELITE_JOBS);
