/* ============================================
   Reborn Infinity - js/jobs/heroJobs.js
   英雄級職業データ（Rank4）
   ============================================ */

const HERO_JOBS = [
  {
    id: 'hero',
    name: '英雄',
    rank: 4,
    category: 'combat',
    icon: '⚡',
    desc: '伝説に名を刻む英雄。全ステータスが大幅に上昇する。',
    income: 120,
    xpBase: 2500,
    reqFame: 100,
    reqLevel: { paladin: 20, warlord: 10 },
    bonuses: { atk: 25, def: 20, hp: 100, fame: 0.25, xp: 0.15 },
    unlockDesc: '名声100・聖騎士Lv20・武将Lv10',
  },
  {
    id: 'dragon_knight',
    name: 'ドラゴンナイト',
    rank: 4,
    category: 'combat',
    icon: '🐲',
    desc: '竜と契約した騎士。圧倒的な攻撃力と防御力を持つ。',
    income: 130,
    xpBase: 2600,
    reqFame: 110,
    reqLevel: { paladin: 20, beastmaster: 10 },
    bonuses: { atk: 35, def: 25, hp: 80, critRate: 0.10 },
    unlockDesc: '名声110・聖騎士Lv20・獣使いLv10',
  },
  {
    id: 'grand_wizard',
    name: '大魔法使い',
    rank: 4,
    category: 'magic',
    icon: '🌈',
    desc: '魔法の頂点に立つ者。全魔法系ステータスが突出する。',
    income: 125,
    xpBase: 2700,
    reqFame: 115,
    reqLevel: { archmage: 20, sage: 10 },
    bonuses: { mp: 100, xp: 0.35, atk: 20, skillXp: 0.20 },
    unlockDesc: '名声115・大魔導士Lv20・賢者Lv10',
  },
  {
    id: 'saint',
    name: '聖人',
    rank: 4,
    category: 'divine',
    icon: '😇',
    desc: '神に最も近い人間。寿命・HP・名声が大幅に伸びる。',
    income: 110,
    xpBase: 2800,
    reqFame: 120,
    reqLevel: { high_priest: 20, sage: 10 },
    bonuses: { hp: 150, lifespan: 15, fame: 0.35, hpRegen: 0.25 },
    unlockDesc: '名声120・大神官Lv20・賢者Lv10',
  },
  {
    id: 'tycoon',
    name: '大富豪',
    rank: 4,
    category: 'commerce',
    icon: '💎',
    desc: '国家さえ動かす財力を持つ者。コイン収入が圧倒的。',
    income: 200,
    xpBase: 3000,
    reqFame: 125,
    reqLevel: { grand_merchant: 20 },
    bonuses: { coin: 0.60, fame: 0.20 },
    unlockDesc: '名声125・大商人Lv20',
  },
  {
    id: 'grand_master_craft',
    name: '匠の神',
    rank: 4,
    category: 'craft',
    icon: '🏆',
    desc: '神の域に達した職人技。クラフト・素材全てが最高峰。',
    income: 115,
    xpBase: 2600,
    reqFame: 110,
    reqLevel: { master_alchemist: 20, blacksmith: 20 },
    bonuses: { craft: 0.50, mat: 0.30, xp: 0.15 },
    unlockDesc: '名声110・錬金術の達人Lv20・鍛冶師Lv20',
  },
  {
    id: 'mythic_explorer',
    name: '神話の探検家',
    rank: 4,
    category: 'explore',
    icon: '🗺️',
    desc: '世界の果てまで踏破した伝説の探検家。',
    income: 118,
    xpBase: 2550,
    reqFame: 105,
    reqLevel: { beastmaster: 20, ranger: 20 },
    bonuses: { explore: 0.45, mat: 0.25, luck: 0.15 },
    unlockDesc: '名声105・獣使いLv20・レンジャーLv20',
  },
  {
    id: 'blade_master',
    name: 'ブレードマスター',
    rank: 4,
    category: 'combat',
    icon: '⚔️',
    desc: '剣技を極めた剣聖。ATKとクリティカルが最高水準。',
    income: 125,
    xpBase: 2500,
    reqFame: 100,
    reqLevel: { shadow_master: 20, runeblade: 15 },
    bonuses: { atk: 40, critRate: 0.15, critMult: 0.5 },
    unlockDesc: '名声100・影の主Lv20・ルーンブレードLv15',
  },
];

Object.freeze(HERO_JOBS);
