/* ============================================
   Reborn Infinity - js/jobs/villagerJobs.js
   村人級職業データ（Rank0）
   ============================================ */

const VILLAGER_JOBS = [
  {
    id: 'villager',
    name: '村人',
    rank: 0,
    category: 'life',
    icon: '🏠',
    desc: '何でもこなす村の働き手。すべての始まり。',
    income: 1,
    xpBase: 100,
    reqFame: 0,
    reqLevel: {},
    bonuses: { coin: 0.01 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'woodcutter',
    name: '木こり',
    rank: 0,
    category: 'gather',
    icon: '🪓',
    desc: '木を伐採して素材を集める。',
    income: 2,
    xpBase: 120,
    reqFame: 0,
    reqLevel: {},
    bonuses: { mat: 0.05 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'farmer',
    name: '農夫',
    rank: 0,
    category: 'gather',
    icon: '🌾',
    desc: '畑を耕し作物を育てる。素材獲得量が増える。',
    income: 3,
    xpBase: 150,
    reqFame: 0,
    reqLevel: {},
    bonuses: { mat: 0.08, coin: 0.02 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'fisherman',
    name: '漁師',
    rank: 0,
    category: 'gather',
    icon: '🎣',
    desc: '川や海で魚を釣る。',
    income: 3,
    xpBase: 140,
    reqFame: 0,
    reqLevel: {},
    bonuses: { mat: 0.06, luck: 0.02 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'gatherer',
    name: '採集者',
    rank: 0,
    category: 'gather',
    icon: '🌿',
    desc: '山野で薬草・素材を採集する。',
    income: 2,
    xpBase: 130,
    reqFame: 0,
    reqLevel: {},
    bonuses: { mat: 0.10 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'trader',
    name: '行商人',
    rank: 0,
    category: 'commerce',
    icon: '🛒',
    desc: '村を回って物を売り買いする。',
    income: 5,
    xpBase: 180,
    reqFame: 5,
    reqLevel: {},
    bonuses: { coin: 0.08 },
    unlockDesc: '名声5が必要',
  },
  {
    id: 'porter',
    name: '荷運び人',
    rank: 0,
    category: 'life',
    icon: '📦',
    desc: '荷物を運んで日銭を稼ぐ。',
    income: 2,
    xpBase: 110,
    reqFame: 0,
    reqLevel: {},
    bonuses: { hp: 5 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'cook',
    name: '料理人見習い',
    rank: 0,
    category: 'craft',
    icon: '🍳',
    desc: '厨房で下働きをする。クラフト効率が少し上がる。',
    income: 3,
    xpBase: 160,
    reqFame: 3,
    reqLevel: {},
    bonuses: { craft: 0.05, coin: 0.02 },
    unlockDesc: '名声3が必要',
  },
  {
    id: 'stable_hand',
    name: '馬丁',
    rank: 0,
    category: 'life',
    icon: '🐴',
    desc: '馬の世話をする。ペット親和性が上がる。',
    income: 2,
    xpBase: 120,
    reqFame: 0,
    reqLevel: {},
    bonuses: { petXp: 0.05 },
    unlockDesc: '最初から使用可能',
  },
  {
    id: 'miner',
    name: '鉱夫',
    rank: 0,
    category: 'gather',
    icon: '⛏️',
    desc: '鉱山で鉱石を掘る。素材を大量に集められる。',
    income: 4,
    xpBase: 200,
    reqFame: 8,
    reqLevel: {},
    bonuses: { mat: 0.15 },
    unlockDesc: '名声8が必要',
  },
];

Object.freeze(VILLAGER_JOBS);
